In [92]:
# Import libraries
import pandas as pd
from pandas import DataFrame
import numpy as np
#pd.set_option('display.max_columns', None)  
import seaborn as sns
from sklearn.metrics import roc_auc_score

In [93]:
#Import data for model building and prediction
model_data=pd.read_csv('data/final_model_data')

In [94]:
model_data.head(2)

drug_1         drug_2  Diarrhoea  Dyspnoea  Nausea  Pneumonia  Pyrexia  \
0  acarbose     acebutolol          0         1       0          0        1   
1  acarbose  acenocoumarol          1         1       0          0        1   

   Vomiting  0_sub  1_sub  ...  871_sub  872_sub  873_sub  874_sub  875_sub  \
0         0      1      1  ...        0        0        0        0        0   
1         1      1      1  ...        0        0        0        0        0   

   876_sub  877_sub  878_sub  879_sub  880_sub  
0        0        0        0        0        0  
1        0        0        0        0        0  

[2 rows x 889 columns]

In [95]:
#hamming distance- to assess how good predictions are, on an average. - for multiclass 
#

In [96]:
model_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123069 entries, 0 to 123068
Columns: 889 entries, drug_1 to 880_sub
dtypes: int64(887), object(2)
memory usage: 834.7+ MB


In [97]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, \
classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression

## Prediction for Diarrhoea

In [98]:
X=model_data.iloc[:,8:]
y=model_data.iloc[:, 2]

## oversampling for Diarrhoea

In [99]:
#create development and hold out set
X_dev, X_hold, y_dev, y_hold = train_test_split(X, y, stratify=y, test_size = 0.2, random_state=321)

In [100]:
X_train, X_test, y_train, y_test= train_test_split(X_dev, y_dev, stratify=y_dev, test_size=0.2, \
                                                  random_state=321)

In [101]:
oversampler = RandomOverSampler(random_state = 321)

X_resampled, y_resampled = oversampler.fit_resample(X_train, y_train)

In [102]:
type(X_train)

pandas.core.frame.DataFrame

In [103]:
clf = LogisticRegression()

In [104]:
clf.fit(X_resampled, y_resampled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [105]:
probas = clf.predict_proba(X_resampled)
preds = clf.predict(X_resampled)

In [106]:
#print(X_train.head(1))
print(probas[0])
print(preds[0])

[0.54131039 0.45868961]
0


In [107]:
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)

In [108]:
print(y_pred_proba[0])

[0.49147031 0.50852969]


In [109]:
accuracy_score(y_test, y_pred)

0.6016962063887055

In [110]:
print(confusion_matrix(y_test, y_pred))

[[2196 2116]
 [5727 9652]]


In [111]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.28      0.51      0.36      4312
           1       0.82      0.63      0.71     15379

    accuracy                           0.60     19691
   macro avg       0.55      0.57      0.54     19691
weighted avg       0.70      0.60      0.63     19691



In [112]:
roc_auc_score(y_test, y_pred)

0.568442757580543

### Predicting Dyspnoea (difficulty breathing)

In [113]:
X1=model_data.iloc[:,8:]
y1=model_data.iloc[:,3]

In [114]:
#create development and hold out set
X1_dev, X1_hold, y1_dev, y1_hold = train_test_split(X1, y1, stratify=y1, test_size = 0.2, \
                                                    random_state=321)

In [115]:
X1_train, X1_test, y1_train, y1_test= train_test_split(X1_dev, y1_dev, stratify=y_dev, \
                                                       test_size=0.2, \
                                                  random_state=321)

In [116]:
oversampler = RandomOverSampler(random_state = 321)

X1_resampled, y1_resampled = oversampler.fit_resample(X1_train, y1_train)

In [117]:
clf.fit(X1_resampled, y1_resampled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [118]:
probas1 = clf.predict_proba(X1_resampled)
preds1 = clf.predict(X1_resampled)

In [119]:
#print(X1_train.head(1))
print(probas1[0])
print(preds1[0])

[0.50507661 0.49492339]
0


In [120]:
y_pred1 = clf.predict(X1_test)
y_pred_proba1 = clf.predict_proba(X1_test)

In [121]:
print(y_pred_proba1[0])

[0.59098663 0.40901337]


In [122]:
accuracy_score(y1_test, y_pred1)

0.57671017215987

In [123]:
print(confusion_matrix(y1_test, y_pred1))

[[2116 1746]
 [6589 9240]]


In [124]:
print(classification_report(y1_test, y_pred1))

              precision    recall  f1-score   support

           0       0.24      0.55      0.34      3862
           1       0.84      0.58      0.69     15829

    accuracy                           0.58     19691
   macro avg       0.54      0.57      0.51     19691
weighted avg       0.72      0.58      0.62     19691



In [125]:
roc_auc_score(y1_test, y_pred1)

0.5658206742771553

### Predicting Nausea 

In [126]:
X2=model_data.iloc[:,8:]
y2=model_data.iloc[:,4]

In [127]:
#create development and hold out set
X2_dev, X2_hold, y2_dev, y2_hold = train_test_split(X2, y2, stratify=y2, test_size = 0.2, \
                                                    random_state=321)

In [128]:
X2_train, X2_test, y2_train, y2_test= train_test_split(X2_dev, y2_dev, stratify=y_dev, \
                                                       test_size=0.2, \
                                                  random_state=321)

In [129]:
oversampler = RandomOverSampler(random_state = 321)

X2_resampled, y2_resampled = oversampler.fit_resample(X2_train, y2_train)

In [130]:
clf.fit(X2_resampled, y2_resampled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [131]:
probas2 = clf.predict_proba(X2_resampled)
preds2 = clf.predict(X2_resampled)

In [132]:
#print(X3_train.head(1))
print(probas2[0])
print(preds2[0])

[0.42632671 0.57367329]
1


In [133]:
y_pred2 = clf.predict(X2_test)
y_pred_proba2 = clf.predict_proba(X2_test)

In [134]:
print(y_pred_proba2[0])

[0.44475438 0.55524562]


In [135]:
accuracy_score(y2_test, y_pred2)

0.6113960692702249

In [136]:
print(confusion_matrix(y2_test, y_pred2))

[[ 1780  1711]
 [ 5941 10259]]


In [137]:
print(classification_report(y2_test, y_pred2))

              precision    recall  f1-score   support

           0       0.23      0.51      0.32      3491
           1       0.86      0.63      0.73     16200

    accuracy                           0.61     19691
   macro avg       0.54      0.57      0.52     19691
weighted avg       0.75      0.61      0.66     19691



In [138]:
roc_auc_score(y2_test, y_pred2)

0.5715770800400324

## Prediction for Pneumonia

In [139]:
X3=model_data.iloc[:,8:]
y3=model_data.iloc[:, 5]

In [140]:
#create development and hold out set
X3_dev, X3_hold, y3_dev, y3_hold = train_test_split(X3, y3, stratify=y3, test_size = 0.2, \
                                                    random_state=321)

In [141]:
X3_train, X3_test, y3_train, y3_test= train_test_split(X3_dev, y3_dev, stratify=y_dev, \
                                                       test_size=0.2, \
                                                  random_state=321)

In [142]:
oversampler = RandomOverSampler(random_state = 321)

X3_resampled, y3_resampled = oversampler.fit_resample(X3_train, y3_train)

In [143]:
clf.fit(X3_resampled, y3_resampled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [144]:
probas3 = clf.predict_proba(X3_resampled)
preds3 = clf.predict(X3_resampled)

In [145]:
#print(X4_train.head(1))
print(probas3[0])
print(preds3[0])

[0.61099401 0.38900599]
0


In [146]:
y_pred3 = clf.predict(X3_test)
y_pred_proba3 = clf.predict_proba(X3_test)

In [147]:
print(y_pred_proba3[0])

[0.65473949 0.34526051]


In [148]:
accuracy_score(y3_test, y_pred3)

0.5860037580620588

In [149]:
print(confusion_matrix(y3_test, y_pred3))

[[2575 2727]
 [5425 8964]]


In [150]:
print(classification_report(y3_test, y_pred3))

              precision    recall  f1-score   support

           0       0.32      0.49      0.39      5302
           1       0.77      0.62      0.69     14389

    accuracy                           0.59     19691
   macro avg       0.54      0.55      0.54     19691
weighted avg       0.65      0.59      0.61     19691



In [151]:
roc_auc_score(y3_test, y_pred3)

0.5543208354258837

## Prediction for Pyrexia (Fever)

In [152]:
X4=model_data.iloc[:,8:]
y4=model_data.iloc[:, 6]

In [153]:
#create development and hold out set
X4_dev, X4_hold, y4_dev, y4_hold = train_test_split(X4, y4, stratify=y4, test_size = 0.2, \
                                                    random_state=321)

In [154]:
X4_train, X4_test, y4_train, y4_test= train_test_split(X4_dev, y4_dev, stratify=y_dev, \
                                                       test_size=0.2, \
                                                  random_state=321)

In [155]:
oversampler = RandomOverSampler(random_state = 321)

X4_resampled, y4_resampled = oversampler.fit_resample(X4_train, y4_train)

In [156]:
clf.fit(X4_resampled, y4_resampled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [157]:
probas4 = clf.predict_proba(X4_resampled)
preds4 = clf.predict(X4_resampled)

In [158]:
#print(X5_train.head(1))
print(probas4[0])
print(preds4[0])

[0.47661412 0.52338588]
1


In [159]:
y_pred4 = clf.predict(X4_test)
y_pred_proba4 = clf.predict_proba(X4_test)

In [160]:
print(y_pred_proba4[0])

[0.45217006 0.54782994]


In [161]:
accuracy_score(y4_test, y_pred4)

0.5877304352242141

In [162]:
print(confusion_matrix(y4_test, y_pred4))

[[2513 2462]
 [5656 9060]]


In [163]:
print(classification_report(y4_test, y_pred4))

              precision    recall  f1-score   support

           0       0.31      0.51      0.38      4975
           1       0.79      0.62      0.69     14716

    accuracy                           0.59     19691
   macro avg       0.55      0.56      0.54     19691
weighted avg       0.67      0.59      0.61     19691



In [164]:
roc_auc_score(y4_test, y_pred4)

0.5603910282589899

## Prediction for Vomiting

In [165]:
X5=model_data.iloc[:,8:]
y5=model_data.iloc[:, 7]

In [166]:
#create development and hold out set
X5_dev, X5_hold, y5_dev, y5_hold = train_test_split(X5, y5, stratify=y5, test_size = 0.2, random_state=321)

In [167]:
X5_train, X5_test, y5_train, y5_test= train_test_split(X5_dev, y5_dev, stratify=y_dev, \
                                                       test_size=0.2, \
                                                  random_state=321)

In [168]:
X5_resampled, y5_resampled = oversampler.fit_resample(X5_train, y5_train)

In [169]:
clf.fit(X5_resampled, y5_resampled)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [170]:
probas5 = clf.predict_proba(X5_resampled)
preds5 = clf.predict(X5_resampled)

In [171]:
#print(X6_train.head(1))
print(probas5[0])
print(preds5[0])

[0.73613431 0.26386569]
0


In [172]:
y_pred5 = clf.predict(X5_test)
y_pred_proba5 = clf.predict_proba(X5_test)

In [173]:
print(y_pred_proba5[0])

[0.56781913 0.43218087]


In [174]:
accuracy_score(y5_test, y_pred5)

0.5775735107409476

In [175]:
print(confusion_matrix(y5_test, y_pred5))

[[2385 2030]
 [6288 8988]]


In [176]:
print(classification_report(y5_test, y_pred5))

              precision    recall  f1-score   support

           0       0.27      0.54      0.36      4415
           1       0.82      0.59      0.68     15276

    accuracy                           0.58     19691
   macro avg       0.55      0.56      0.52     19691
weighted avg       0.69      0.58      0.61     19691



In [177]:
roc_auc_score(y5_test, y_pred5)

0.5642888851919694

In [178]:

#pip install scikit-multilearn

In [179]:
#from skmultilearn.adapt import MLkNN

In [180]:
#classifier = MLkNN(k=20)

In [181]:
#from skmultilearn.problem_transform import BinaryRelevance