In [2]:
# Import libraries
import pandas as pd
from pandas import DataFrame
import numpy as np
#pd.set_option('display.max_columns', None)  
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV

In [4]:
#Import data for model building and prediction
rf_model_data=pd.read_csv('data/final_model_data')

In [5]:
rf_model_data.head(2)

drug_1         drug_2  Diarrhoea  Dyspnoea  Nausea  Pneumonia  Pyrexia  \
0  acarbose     acebutolol          0         1       0          0        1   
1  acarbose  acenocoumarol          1         1       0          0        1   

   Vomiting  0_sub  1_sub  ...  871_sub  872_sub  873_sub  874_sub  875_sub  \
0         0      1      1  ...        0        0        0        0        0   
1         1      1      1  ...        0        0        0        0        0   

   876_sub  877_sub  878_sub  879_sub  880_sub  
0        0        0        0        0        0  
1        0        0        0        0        0  

[2 rows x 889 columns]


## Random Forest for Diarrhoea

In [6]:
X=rf_model_data.iloc[:,8:]
y=rf_model_data.iloc[:, 2]

### oversampling for Diarrhoea

In [7]:
#create development and hold out set
X_dev, X_hold, y_dev, y_hold = train_test_split(X, y, test_size = 0.2, random_state=321)

In [8]:
X_train, X_test, y_train, y_test= train_test_split(X_dev, y_dev, test_size=0.2, \
                                                  random_state=321)

In [9]:
from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler(random_state = 321)

X_resampled, y_resampled = oversampler.fit_resample(X_train, y_train)

#y_resampled.value_counts()

In [10]:
#RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier


#number of estimator:number of trees and depth: criteria to split
#param_grid = {'n_estimators': 50, 'max_depth': 5}
random_forest = RandomForestClassifier(random_state=321)

# Instantiate the GridSearchCV object: logreg_cv
#random_forest_cv = GridSearchCV(random_forest, param_grid, cv=5)
random_forest.fit(X_resampled, y_resampled)

# Model evaluating
#MAE_forest = statistics.mean(abs(y_pred-y_test))

# Print the optimal parameters and best score
#print("Tuned Random Forest Parameter: {}".format(random_forest_cv.best_params_))
#print("Tuned Random Forest score: {}".format(random_forest_cv.score(X_test,y_test)))
#print("Tuned Random Forest MAE: "+str(MAE_forest))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=321,
                       verbose=0, warm_start=False)

In [11]:
# Model testing
accuracy_score(y_resampled, random_forest.predict(X_resampled))

0.5818226239921818

In [12]:
y_pred = random_forest.predict(X_test)
accuracy_score(y_test, y_pred)

0.5929612513330963

In [13]:
confusion_matrix(y_test, y_pred)

array([[2353, 1947],
       [6068, 9323]])

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.28      0.55      0.37      4300
           1       0.83      0.61      0.70     15391

    accuracy                           0.59     19691
   macro avg       0.55      0.58      0.53     19691
weighted avg       0.71      0.59      0.63     19691



# ## Random Forest for Dyspnoea

In [15]:
X1=rf_model_data.iloc[:,8:]
y1=rf_model_data.iloc[:,3]

### oversampling for Dyspnoea

In [16]:
#create development and hold out set
X1_dev, X1_hold, y1_dev, y1_hold = train_test_split(X1, y1, test_size = 0.2, \
                                                    random_state=321)

In [17]:
X1_train, X1_test, y1_train, y1_test= train_test_split(X1_dev, y1_dev, test_size=0.2, \
                                                  random_state=321)

In [18]:
from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler(random_state = 321)

X1_resampled, y1_resampled = oversampler.fit_resample(X1_train, y1_train)

#y_resampled.value_counts()

In [19]:
#RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier

#number of estimator:number of trees and depth: criteria to split
#param_grid = {'n_estimators': 50, 'max_depth': 5}
rf1 = RandomForestClassifier(random_state=321)

# Instantiate the GridSearchCV object: logreg_cv
#random_forest_cv = GridSearchCV(random_forest, param_grid, cv=5)
rf1.fit(X1_resampled, y1_resampled)

# Model evaluating
#MAE_forest = statistics.mean(abs(y_pred-y_test))

# Print the optimal parameters and best score
#print("Tuned Random Forest Parameter: {}".format(random_forest_cv.best_params_))
#print("Tuned Random Forest score: {}".format(random_forest_cv.score(X_test,y_test)))
#print("Tuned Random Forest MAE: "+str(MAE_forest))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=321,
                       verbose=0, warm_start=False)

In [20]:
# Model testing
accuracy_score(y1_resampled, rf1.predict(X1_resampled))

0.5838784787670473

In [21]:
y_pred1 = rf1.predict(X1_test)
accuracy_score(y1_test, y_pred1)

0.5886445584277081

In [23]:
confusion_matrix(y_test, y_pred1)

array([[2179, 2121],
       [6271, 9120]])

In [24]:
print(classification_report(y1_test, y_pred1))

              precision    recall  f1-score   support

           0       0.25      0.54      0.35      3920
           1       0.84      0.60      0.70     15771

    accuracy                           0.59     19691
   macro avg       0.55      0.57      0.52     19691
weighted avg       0.72      0.59      0.63     19691



# ## Random Forest for Nausea

In [25]:
X2=rf_model_data.iloc[:,8:]
y2=rf_model_data.iloc[:,4]

### oversampling for Nausea

In [26]:
#create development and hold out set
X2_dev, X2_hold, y2_dev, y2_hold = train_test_split(X2, y2, test_size = 0.2, \
                                                    random_state=321)

In [27]:
X2_train, X2_test, y2_train, y2_test= train_test_split(X2_dev, y2_dev, test_size=0.2, \
                                                  random_state=321)

In [28]:
from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler(random_state = 321)

X2_resampled, y2_resampled = oversampler.fit_resample(X2_train, y2_train)

#y_resampled.value_counts()

In [29]:
#number of estimator:number of trees and depth: criteria to split
#param_grid = {'n_estimators': 50, 'max_depth': 5}
rf2 = RandomForestClassifier(random_state=321)

# Instantiate the GridSearchCV object: logreg_cv
#random_forest_cv = GridSearchCV(random_forest, param_grid, cv=5)
rf2.fit(X2_resampled, y2_resampled)

# Model evaluating
#MAE_forest = statistics.mean(abs(y_pred-y_test))

# Print the optimal parameters and best score
#print("Tuned Random Forest Parameter: {}".format(random_forest_cv.best_params_))
#print("Tuned Random Forest score: {}".format(random_forest_cv.score(X_test,y_test)))
#print("Tuned Random Forest MAE: "+str(MAE_forest))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=321,
                       verbose=0, warm_start=False)

In [30]:
# Model testing
accuracy_score(y2_resampled, rf2.predict(X2_resampled))

0.5930421086765183

In [31]:
y_pred2 = rf2.predict(X2_test)
accuracy_score(y2_test, y_pred2)

0.6053526992026814

In [32]:
confusion_matrix(y2_test, y_pred2)

array([[1946, 1577],
       [6194, 9974]])

In [33]:
print(classification_report(y2_test, y_pred2))

              precision    recall  f1-score   support

           0       0.24      0.55      0.33      3523
           1       0.86      0.62      0.72     16168

    accuracy                           0.61     19691
   macro avg       0.55      0.58      0.53     19691
weighted avg       0.75      0.61      0.65     19691



# ## Random Forest for Pneumonia

In [34]:
X3=rf_model_data.iloc[:,8:]
y3=rf_model_data.iloc[:,5]

### oversampling for Pneumonia

In [35]:
#create development and hold out set
X3_dev, X3_hold, y3_dev, y3_hold = train_test_split(X3, y3, test_size = 0.2, \
                                                    random_state=321)

In [36]:
X3_train, X3_test, y3_train, y3_test= train_test_split(X3_dev, y3_dev, test_size=0.2, \
                                                  random_state=321)

In [37]:
from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler(random_state = 321)

X3_resampled, y3_resampled = oversampler.fit_resample(X3_train, y3_train)

#y_resampled.value_counts()

In [38]:
#RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier

#number of estimator:number of trees and depth: criteria to split
#param_grid = {'n_estimators': 50, 'max_depth': 5}
rf3 = RandomForestClassifier(random_state=321)

# Instantiate the GridSearchCV object: logreg_cv
#random_forest_cv = GridSearchCV(random_forest, param_grid, cv=5)
rf3.fit(X3_resampled, y3_resampled)

# Model evaluating
#MAE_forest = statistics.mean(abs(y_pred-y_test))

# Print the optimal parameters and best score
#print("Tuned Random Forest Parameter: {}".format(random_forest_cv.best_params_))
#print("Tuned Random Forest score: {}".format(random_forest_cv.score(X_test,y_test)))
#print("Tuned Random Forest MAE: "+str(MAE_forest))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=321,
                       verbose=0, warm_start=False)

In [39]:
# Model testing
accuracy_score(y3_resampled, rf3.predict(X3_resampled))

0.5762926254505129

In [40]:
y_pred3 = rf3.predict(X3_test)
accuracy_score(y3_test, y_pred3)

0.6060128992940937

In [41]:
confusion_matrix(y3_test, y_pred3)

array([[2605, 2685],
       [5073, 9328]])

In [43]:
print(classification_report(y3_test, y_pred3))

              precision    recall  f1-score   support

           0       0.34      0.49      0.40      5290
           1       0.78      0.65      0.71     14401

    accuracy                           0.61     19691
   macro avg       0.56      0.57      0.55     19691
weighted avg       0.66      0.61      0.62     19691



# ## Random Forest for Pyrexia

In [44]:
X4=rf_model_data.iloc[:,8:]
y4=rf_model_data.iloc[:,6]

### oversampling for Pyrexia

In [45]:
#create development and hold out set
X4_dev, X4_hold, y4_dev, y4_hold = train_test_split(X4, y4, test_size = 0.2, \
                                                    random_state=321)

In [46]:
X4_train, X4_test, y4_train, y4_test= train_test_split(X4_dev, y4_dev, test_size=0.2, \
                                                  random_state=321)

In [47]:
from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler(random_state = 321)

X4_resampled, y4_resampled = oversampler.fit_resample(X4_train, y4_train)

#y_resampled.value_counts()

In [48]:
#RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier

#number of estimator:number of trees and depth: criteria to split
#param_grid = {'n_estimators': 50, 'max_depth': 5}
rf4 = RandomForestClassifier(random_state=321)

# Instantiate the GridSearchCV object: logreg_cv
#random_forest_cv = GridSearchCV(random_forest, param_grid, cv=5)
rf4.fit(X4_resampled, y4_resampled)

# Model evaluating
#MAE_forest = statistics.mean(abs(y_pred-y_test))

# Print the optimal parameters and best score
#print("Tuned Random Forest Parameter: {}".format(random_forest_cv.best_params_))
#print("Tuned Random Forest score: {}".format(random_forest_cv.score(X_test,y_test)))
#print("Tuned Random Forest MAE: "+str(MAE_forest))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=321,
                       verbose=0, warm_start=False)

In [49]:
# Model testing
accuracy_score(y4_resampled, rf4.predict(X4_resampled))

0.5771547017879077

In [50]:
y_pred4 = rf4.predict(X4_test)
accuracy_score(y4_test, y_pred4)

0.5963638210349906

In [51]:
confusion_matrix(y4_test, y_pred4)

array([[2598, 2467],
       [5481, 9145]])

In [52]:
print(classification_report(y4_test, y_pred4))

              precision    recall  f1-score   support

           0       0.32      0.51      0.40      5065
           1       0.79      0.63      0.70     14626

    accuracy                           0.60     19691
   macro avg       0.55      0.57      0.55     19691
weighted avg       0.67      0.60      0.62     19691



# ## Random Forest for Vomiting

In [53]:
X5=rf_model_data.iloc[:,8:]
y5=rf_model_data.iloc[:,7]

### oversampling for Vomiting

In [54]:
#create development and hold out set
X5_dev, X5_hold, y5_dev, y5_hold = train_test_split(X5, y5, test_size = 0.2, \
                                                    random_state=321)

In [55]:
X5_train, X5_test, y5_train, y5_test= train_test_split(X5_dev, y5_dev, test_size=0.2, \
                                                  random_state=321)

In [56]:
from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler(random_state = 321)

X5_resampled, y5_resampled = oversampler.fit_resample(X5_train, y5_train)

#y_resampled.value_counts()

In [57]:
#RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier

#number of estimator:number of trees and depth: criteria to split
#param_grid = {'n_estimators': 50, 'max_depth': 5}
rf5 = RandomForestClassifier(random_state=321)

# Instantiate the GridSearchCV object: logreg_cv
#random_forest_cv = GridSearchCV(random_forest, param_grid, cv=5)
rf5.fit(X5_resampled, y5_resampled)

# Model evaluating
#MAE_forest = statistics.mean(abs(y_pred-y_test))

# Print the optimal parameters and best score
#print("Tuned Random Forest Parameter: {}".format(random_forest_cv.best_params_))
#print("Tuned Random Forest score: {}".format(random_forest_cv.score(X_test,y_test)))
#print("Tuned Random Forest MAE: "+str(MAE_forest))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=321,
                       verbose=0, warm_start=False)

In [58]:
# Model testing
accuracy_score(y5_resampled, rf5.predict(X5_resampled))

0.5753803596127247

In [59]:
y_pred5 = rf5.predict(X5_test)
accuracy_score(y5_test, y_pred5)

0.5946371438728353

In [61]:
confusion_matrix(y5_test, y_pred5)

array([[2285, 2234],
       [5748, 9424]])

In [62]:
print(classification_report(y5_test, y_pred5))

              precision    recall  f1-score   support

           0       0.28      0.51      0.36      4519
           1       0.81      0.62      0.70     15172

    accuracy                           0.59     19691
   macro avg       0.55      0.56      0.53     19691
weighted avg       0.69      0.59      0.62     19691



In [60]:
lr = LogisticRegression()
lr.fit(X_resampled, y_resampled)

y_pred = lr.predict(X_test)
accuracy_score(y_test, y_pred)

confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))
from imblearn.under_sampling import RandomUnderSampler

NameError: name 'LogisticRegression' is not defined