In [1]:
# Import libraries
import pandas as pd
from pandas import DataFrame
import numpy as np
#pd.set_option('display.max_columns', None)  
import seaborn as sns
import xgboost as xgb

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, \
classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

In [3]:
#Import data for model building and prediction
xgbmodel_data=pd.read_csv('data/final_model_data')

In [4]:
xgbmodel_data.head()

drug_1         drug_2  Diarrhoea  Dyspnoea  Nausea  Pneumonia  Pyrexia  \
0  acarbose     acebutolol          0         1       0          0        1   
1  acarbose  acenocoumarol          1         1       0          0        1   
2  acarbose      acyclovir          1         0       0          1        0   
3  acarbose    alendronate          1         1       1          0        1   
4  acarbose   alfacalcidol          0         0       1          0        1   

   Vomiting  0_sub  1_sub  ...  871_sub  872_sub  873_sub  874_sub  875_sub  \
0         0      1      1  ...        0        0        0        0        0   
1         1      1      1  ...        0        0        0        0        0   
2         0      1      1  ...        0        0        0        0        0   
3         0      1      1  ...        0        0        0        0        0   
4         0      1      1  ...        0        0        0        0        0   

   876_sub  877_sub  878_sub  879_sub  880_sub  
0        0        0        0        0        0  
1        0        0        0        0        0  
2        0        0        0        0        0  
3        0        0        0        0        0  
4        0        0        0        0        0  

[5 rows x 889 columns]

# XGBClassifier for Diarrhoea

In [5]:
X=xgbmodel_data.iloc[:,8:]
y=xgbmodel_data[['Diarrhoea']]

### oversampling for Diarrhoea

In [6]:
#create development and hold out set
X_dev, X_hold, y_dev, y_hold = train_test_split(X, y, stratify=y, test_size = 0.2, random_state=321)

In [7]:
X_train, X_test, y_train, y_test= train_test_split(X_dev, y_dev, stratify=y_dev, \
                                                   test_size=0.2, random_state=321)

In [8]:
oversampler = RandomOverSampler(random_state = 321)

X_resampled, y_resampled = oversampler.fit_resample(X_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
# fit model 
clf = XGBClassifier()

In [10]:
clf.fit(X_resampled, y_resampled)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=0.2, gamma=0,
              gpu_id=-1, importance_type='gain', interaction_constraints=None,
              learning_rate=0.200000003, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [11]:
probas = clf.predict_proba(X_resampled)
preds = clf.predict(X_resampled)

In [12]:
#print(X_resampled[1])
print(probas[0])
print(preds[0])

[0.5396538 0.4603462]
0


In [13]:

y_pred = clf.predict(X_test.values)
y_pred_proba = clf.predict_proba(X_test.values)

In [14]:
accuracy_score(y_test, y_pred)

0.6129196079427149

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.28      0.50      0.36      4312
           1       0.82      0.64      0.72     15379

    accuracy                           0.61     19691
   macro avg       0.55      0.57      0.54     19691
weighted avg       0.70      0.61      0.64     19691



In [16]:
confusion_matrix(y_test, y_pred)

array([[2156, 2156],
       [5466, 9913]])

In [20]:
roc_auc_score(y_test, y_pred)

0.5722901358996033

# XGBClassifier for Dyspnoea

In [22]:
X1=xgbmodel_data.iloc[:,8:]
y1=xgbmodel_data[['Dyspnoea']]

### oversampling for Dysnpoea

In [23]:
#create development and hold out set
X1_dev, X1_hold, y1_dev, y1_hold = train_test_split(X1, y1, stratify=y1, test_size = 0.2,\
                                                    random_state=321)

In [24]:
X1_train, X1_test, y1_train, y1_test= train_test_split(X1_dev, y1_dev, stratify=y1_dev, \
                                                   test_size=0.2, random_state=321)

In [25]:

X1_resampled, y1_resampled = oversampler.fit_resample(X1_train, y1_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
# fit model 
clf = XGBClassifier()

In [27]:
clf.fit(X1_resampled, y1_resampled)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [28]:
probas1 = clf.predict_proba(X1_resampled)
preds1 = clf.predict(X1_resampled)

In [29]:
#print(X_resampled[1])
print(probas1[0])
print(preds1[0])

[0.62499535 0.37500462]
0


In [30]:

y1_pred = clf.predict(X1_test.values)
y1_pred_proba = clf.predict_proba(X1_test.values)

In [31]:
accuracy_score(y1_test, y1_pred)

0.5992077598903052

In [32]:
print(classification_report(y1_test, y1_pred))

              precision    recall  f1-score   support

           0       0.25      0.52      0.34      3892
           1       0.84      0.62      0.71     15799

    accuracy                           0.60     19691
   macro avg       0.55      0.57      0.53     19691
weighted avg       0.72      0.60      0.64     19691



In [33]:
confusion_matrix(y1_test, y1_pred)

array([[2028, 1864],
       [6028, 9771]])

In [34]:
roc_auc_score(y1_test, y1_pred)

0.5697628617784296

# XGBClassifier for Nausea

In [35]:
X2=xgbmodel_data.iloc[:,8:]
y2=xgbmodel_data[['Nausea']]

### oversampling for Nausea

In [36]:
#create development and hold out set
X2_dev, X2_hold, y2_dev, y2_hold = train_test_split(X2, y2, stratify=y2, test_size = 0.2, \
                                                    random_state=321)

In [37]:
X2_train, X2_test, y2_train, y2_test= train_test_split(X2_dev, y2_dev, stratify=y2_dev, \
                                                   test_size=0.2, random_state=321)

In [38]:


X2_resampled, y2_resampled = oversampler.fit_resample(X2_train, y2_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [40]:
clf.fit(X2_resampled, y2_resampled)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [41]:
probas2 = clf.predict_proba(X2_resampled)
preds2 = clf.predict(X2_resampled)

In [42]:
#print(X_resampled[1])
print(probas2[0])
print(preds2[0])

[0.64429396 0.35570604]
0


In [43]:

y2_pred = clf.predict(X2_test.values)
y2_pred_proba = clf.predict_proba(X2_test.values)

In [44]:
accuracy_score(y2_test, y2_pred)

0.6019501295007872

In [45]:
print(classification_report(y2_test, y2_pred))

              precision    recall  f1-score   support

           0       0.23      0.54      0.32      3497
           1       0.86      0.62      0.72     16194

    accuracy                           0.60     19691
   macro avg       0.55      0.58      0.52     19691
weighted avg       0.75      0.60      0.65     19691



In [46]:
confusion_matrix(y2_test, y2_pred)

array([[1878, 1619],
       [6219, 9975]])

In [47]:
roc_auc_score(y2_test, y2_pred)

0.576500309427347

# XGBClassifier for Pneumonia

In [48]:
X3=xgbmodel_data.iloc[:,8:]
y3=xgbmodel_data[['Diarrhoea']]

### oversampling for Pneumonia

In [49]:
#create development and hold out set
X3_dev, X3_hold, y3_dev, y3_hold = train_test_split(X3, y3, stratify=y3, test_size = 0.2, random_state=321)

In [50]:
X3_train, X3_test, y3_train, y3_test= train_test_split(X3_dev, y3_dev, stratify=y3_dev, \
                                                   test_size=0.2, random_state=321)

In [51]:

X3_resampled, y3_resampled = oversampler.fit_resample(X3_train, y3_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [53]:
clf.fit(X3_resampled, y3_resampled)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=0.2, gamma=0,
              gpu_id=-1, importance_type='gain', interaction_constraints=None,
              learning_rate=0.200000003, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [54]:
probas3 = clf.predict_proba(X3_resampled)
preds3 = clf.predict(X3_resampled)

In [55]:
#print(X_resampled[1])
print(probas3[0])
print(preds3[0])

[0.5396538 0.4603462]
0


In [56]:

y3_pred = clf.predict(X3_test.values)
y3_pred_proba = clf.predict_proba(X3_test.values)

In [57]:
accuracy_score(y3_test, y3_pred)

0.6129196079427149

In [58]:
print(classification_report(y3_test, y3_pred))

              precision    recall  f1-score   support

           0       0.28      0.50      0.36      4312
           1       0.82      0.64      0.72     15379

    accuracy                           0.61     19691
   macro avg       0.55      0.57      0.54     19691
weighted avg       0.70      0.61      0.64     19691



In [59]:
confusion_matrix(y3_test, y3_pred)

array([[2156, 2156],
       [5466, 9913]])

In [60]:
roc_auc_score(y3_test, y3_pred)

0.5722901358996033

# XGBClassifier for Pyrexia

In [61]:
X4=xgbmodel_data.iloc[:,8:]
y4=xgbmodel_data[['Pyrexia']]

### oversampling for Pyrexia

In [62]:
#create development and hold out set
X4_dev, X4_hold, y4_dev, y4_hold = train_test_split(X4, y4, stratify=y4, test_size = 0.2, random_state=321)

In [63]:
X4_train, X4_test, y4_train, y4_test= train_test_split(X4_dev, y4_dev, stratify=y4_dev, \
                                                   test_size=0.2, random_state=321)

In [64]:

X4_resampled, y4_resampled = oversampler.fit_resample(X4_train, y4_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [66]:
clf.fit(X4_resampled, y4_resampled)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=0.2, gamma=0,
              gpu_id=-1, importance_type='gain', interaction_constraints=None,
              learning_rate=0.200000003, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [67]:
probas4 = clf.predict_proba(X4_resampled)
preds4 = clf.predict(X4_resampled)

In [68]:
#print(X_resampled[1])
print(probas4[0])
print(preds4[0])

[0.53734636 0.46265364]
0


In [69]:

y4_pred = clf.predict(X4_test.values)
y4_pred_proba = clf.predict_proba(X4_test.values)

In [70]:
accuracy_score(y4_test, y4_pred)

0.5659438322076076

In [71]:
print(classification_report(y4_test, y4_pred))

              precision    recall  f1-score   support

           0       0.30      0.53      0.39      5021
           1       0.78      0.58      0.66     14670

    accuracy                           0.57     19691
   macro avg       0.54      0.56      0.52     19691
weighted avg       0.66      0.57      0.59     19691



In [72]:
confusion_matrix(y4_test, y4_pred)

array([[2680, 2341],
       [6206, 8464]])

In [73]:
roc_auc_score(y4_test, y4_pred)

0.5553589986813392

# XGBClassifier for Vomiting

In [74]:
X5=xgbmodel_data.iloc[:,8:]
y5=xgbmodel_data[['Vomiting']]

### oversampling for Diarrhoea

In [75]:
#create development and hold out set
X5_dev, X5_hold, y5_dev, y5_hold = train_test_split(X5, y5, stratify=y5, test_size = 0.2, \
                                                    random_state=321)

In [76]:
X5_train, X5_test, y5_train, y5_test= train_test_split(X5_dev, y5_dev, stratify=y5_dev, \
                                                   test_size=0.2, random_state=321)

In [77]:
X5_resampled, y5_resampled = oversampler.fit_resample(X5_train, y5_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [78]:
clf.fit(X5_resampled, y5_resampled)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=0.2, gamma=0,
              gpu_id=-1, importance_type='gain', interaction_constraints=None,
              learning_rate=0.200000003, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [79]:
probas5 = clf.predict_proba(X5_resampled)
preds5 = clf.predict(X5_resampled)

In [80]:
#print(X_resampled[1])
print(probas5[0])
print(preds5[0])

[0.549081   0.45091897]
0


In [81]:

y5_pred = clf.predict(X5_test.values)
y5_pred_proba = clf.predict_proba(X5_test.values)

In [82]:
accuracy_score(y5_test, y5_pred)

0.5748311411304657

In [83]:
print(classification_report(y5_test, y5_pred))

              precision    recall  f1-score   support

           0       0.27      0.53      0.36      4494
           1       0.81      0.59      0.68     15197

    accuracy                           0.57     19691
   macro avg       0.54      0.56      0.52     19691
weighted avg       0.69      0.57      0.61     19691



In [84]:
confusion_matrix(y5_test, y5_pred)

array([[2366, 2128],
       [6244, 8953]])

In [85]:
roc_auc_score(y5_test, y5_pred)

0.5578045921098134

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

from sklearn.model_selection import GridSearchCV

clf = xgb.XGBClassifier()
parameters = {
     "eta"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
     "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
     "min_child_weight" : [ 1, 3, 5, 7 ],
     "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
     "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
     }

grid = GridSearchCV(clf,
                    parameters, n_jobs=4,
                    scoring="neg_log_loss",
                    cv=3)

grid.fit(X_train, Y_train)

In [ ]:
#D_train = xgb.DMatrix(X_resampled, label=y_resampled)
#D_test = xgb.DMatrix(X_test, label=y_test)